//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_mrGuard.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Order
    {
        public int Order_ID { get; set; }
        public int Product_ID { get; set; }
        public int C_ID { get; set; }
        [Display(Name = "Total Price")]
        public double Price { get; set; }
        [Display(Name = "Address")]
        public string O_Address { get; set; }
        [Display(Name = "Payment Type")]
        public string Payment_Type { get; set; }
        [Display(Name = "Quantity")]
        public int Order_Quantity { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Product Product { get; set; }
    }
}
