//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_mrGuard.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Review
    {
        public int R_ID { get; set; }

        public int C_ID { get; set; }
        [Display(Name = "Product Name")]
        public int Product_ID { get; set; }
        [Display(Name = "Personal Comment")]
        public string Comment { get; set; }
        [Display(Name = "Rating (1-5)")]
        public double Rating { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Product Product { get; set; }
    }
}
